server:
  port: 8222

eureka:
  client:
    register-with-eureka: false


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/schools/**