

# eureka:
#   instance:
#     hostname: localhost
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka

server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    config:
      student-url: http://localhost:8081/api/v1/students



